# Generated by Django 5.2.7 on 2025-10-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('template', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(max_length=64)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
